{"name": "Переход на вкладку Оплата. Страхователь является застрахованным. Страховая сумма 500000", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\n\nReason: AssertionError: actual text: 2. Ввод данных", "trace": "self = <selene.core.wait.Wait object at 0x0000022AD53AD630>, fn = <selene.core.conditions.ElementCondition object at 0x0000022AD53ADBA0>\n\n    def for_(self, fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self._entity)\n\nentity     = <selene.core.entity.Element object at 0x0000022AD53F62C0>\nfailure    = TimeoutException(\"\\n\\nTimed out after 4s, while waiting for:\\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\\n\\nReason: AssertionError: actual text: 2. Ввод данных\")\nfinish_time = 1666593053.7519088\nfn         = <selene.core.conditions.ElementCondition object at 0x0000022AD53ADBA0>\nreason_message = 'actual text: 2. Ввод данных'\nreason_string = 'AssertionError: actual text: 2. Ввод данных'\nself       = <selene.core.wait.Wait object at 0x0000022AD53AD630>\ntimeout    = 4\n\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\wait.py:102: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selene.core.conditions.ElementCondition object at 0x0000022AD53ADBA0>, entity = <selene.core.entity.Element object at 0x0000022AD53F62C0>\n\n    def __call__(self, entity: E) -> None:\n>       return self._fn(entity)\n\nentity     = <selene.core.entity.Element object at 0x0000022AD53F62C0>\nself       = <selene.core.conditions.ElementCondition object at 0x0000022AD53ADBA0>\n\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\condition.py:151: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nentity = <selene.core.entity.Element object at 0x0000022AD53F62C0>\n\n    def fn(entity: E) -> None:\n        query_to_str = str(query)\n        result = (\n            query.__name__\n            if query_to_str.startswith('<function')\n            else query_to_str\n        )\n        actual = query(entity)\n        if not predicate(actual):\n>           raise AssertionError(f'actual {result}: {actual}')\nE           AssertionError: actual text: 2. Ввод данных\n\nactual     = '2. Ввод данных'\nentity     = <selene.core.entity.Element object at 0x0000022AD53F62C0>\npredicate  = <function includes.<locals>.fn at 0x0000022AD6916B90>\nquery      = <selene.core.wait.Query object at 0x0000022AD5B4D150>\nquery_to_str = 'text'\nresult     = 'text'\n\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\condition.py:124: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.ui.test_form_data.TestCalculateForm object at 0x0000022AD68583D0>\nopen_policy_purchase_form_go_to_data_tab = <function open_policy_purchase_form_go_to_data_tab.<locals>._open at 0x0000022AD6917AC0>\n\n    @allure.title('Переход на вкладку Оплата. Страхователь является застрахованным. Страховая сумма 500000')\n    def test_open_payment_form(self, open_policy_purchase_form_go_to_data_tab):\n        test_data = FormDataBuilder().random_with_add_person().build()\n    \n        policy_form_page = open_policy_purchase_form_go_to_data_tab()\n        policy_form_page.fill_form_data(test_data)\n        policy_form_page.click_on_go_to_payments_tab()\n>       policy_form_page.assure_current_step_name(StepNameData.STEP_PAYMENT)\n\nopen_policy_purchase_form_go_to_data_tab = <function open_policy_purchase_form_go_to_data_tab.<locals>._open at 0x0000022AD6917AC0>\npolicy_form_page = <core.pages.coronavirus_insurance_policy_page.CoronavirusInsurancePolicyPage object at 0x0000022AD53AF520>\nself       = <tests.ui.test_form_data.TestCalculateForm object at 0x0000022AD68583D0>\ntest_data  = FormData(fio='Лариса Олеговна Григорьева', birthday='17.11.1991', doc_data='5613-276830', doc_issue_date='04.06.2012',...inveniamin@ip.info', add_person=True, name_insured=None, date_birth_insured=None, id_insured=None, id_dateInsured=None)\n\ntests\\ui\\test_form_data.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncore\\pages\\coronavirus_insurance_policy_page.py:80: in assure_current_step_name\n    self._current_step_text.should(have.text(value))\n        self       = <core.pages.coronavirus_insurance_policy_page.CoronavirusInsurancePolicyPage object at 0x0000022AD53AF520>\n        value      = <StepNameData.STEP_PAYMENT: '3. Оплата'>\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py:539: in should\n    super().should(condition)\n        __class__  = <class 'selene.core.entity.Element'>\n        condition  = <selene.core.conditions.ElementCondition object at 0x0000022AD53ADBA0>\n        self       = <selene.core.entity.Element object at 0x0000022AD53F62C0>\n        timeout    = None\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py:126: in should\n    self.wait.for_(condition)\n        condition  = <selene.core.conditions.ElementCondition object at 0x0000022AD53ADBA0>\n        self       = <selene.core.entity.Element object at 0x0000022AD53F62C0>\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selene.core.wait.Wait object at 0x0000022AD53AD630>, fn = <selene.core.conditions.ElementCondition object at 0x0000022AD53ADBA0>\n\n        def for_(self, fn: Callable[[E], R]) -> R:\n            finish_time = time.time() + self._timeout\n    \n            while True:\n                try:\n                    return fn(self._entity)\n                except Exception as reason:\n                    if time.time() > finish_time:\n    \n                        reason_message = str(reason)\n    \n                        reason_string = '{name}: {message}'.format(\n                            name=reason.__class__.__name__, message=reason_message\n                        )\n                        # todo: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                        # stacktrace = getattr(reason, 'stacktrace', None)\n                        timeout = self._timeout\n                        entity = self._entity\n    \n                        failure = TimeoutException(\n                            f'''\n    \n    Timed out after {timeout}s, while waiting for:\n    {entity}.{fn}\n    \n    Reason: {reason_string}'''\n                        )\n    \n>                       raise self._hook_failure(failure)\nE                       selene.core.exceptions.TimeoutException: Message: \nE                       \nE                       Timed out after 4s, while waiting for:\nE                       browser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\nE                       \nE                       Reason: AssertionError: actual text: 2. Ввод данных\n\nentity     = <selene.core.entity.Element object at 0x0000022AD53F62C0>\nfailure    = TimeoutException(\"\\n\\nTimed out after 4s, while waiting for:\\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\\n\\nReason: AssertionError: actual text: 2. Ввод данных\")\nfinish_time = 1666593053.7519088\nfn         = <selene.core.conditions.ElementCondition object at 0x0000022AD53ADBA0>\nreason_message = 'actual text: 2. Ввод данных'\nreason_string = 'AssertionError: actual text: 2. Ввод данных'\nself       = <selene.core.wait.Wait object at 0x0000022AD53AD630>\ntimeout    = 4\n\n..\\..\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\wait.py:125: TimeoutException"}, "steps": [{"name": "Переход по адресу: \"https://old.absolutins.ru/kupit-strahovoj-polis/strahovanie-zhizni-i-zdorovya/zashchita-ot-virusa/\"", "status": "passed", "start": 1666593040865, "stop": 1666593046745}, {"name": "Выбрать чекбокс \"Подтверждаю, что -  Отсутствуют лица, проживающие совместно с Застрахованным, у которых диагностирована коронавирусная инфекция COVID-2019 ( код заболевания по МКБ-10 – В 34.2.)\".", "status": "passed", "start": 1666593046746, "stop": 1666593047353}, {"name": "Нажать кнопку \"Продолжить\".", "status": "passed", "start": 1666593047353, "stop": 1666593047606}, {"name": "Заполнить форму \"Ввод данных\"", "status": "passed", "steps": [{"name": "Заполнить поле \"ФИО страхователя\"", "status": "passed", "steps": [{"name": "Ввести значение: Лариса Олеговна Григорьева", "status": "passed", "start": 1666593047607, "stop": 1666593048046}], "parameters": [{"name": "value", "value": "'Лариса Олеговна Григорьева'"}], "start": 1666593047607, "stop": 1666593048046}, {"name": "Заполнить поле \"Дата рождения страхователя\"", "status": "passed", "steps": [{"name": "Ввести значение: 17.11.1991", "status": "passed", "start": 1666593048047, "stop": 1666593048097}], "parameters": [{"name": "value", "value": "'17.11.1991'"}], "start": 1666593048046, "stop": 1666593048097}, {"name": "Заполнить поле \"Серия/номер паспорта страхователя\"", "status": "passed", "steps": [{"name": "Ввести значение: 5613-276830", "status": "passed", "start": 1666593048097, "stop": 1666593048119}], "parameters": [{"name": "value", "value": "'5613-276830'"}], "start": 1666593048097, "stop": 1666593048119}, {"name": "Заполнить поле \"Дата выдачи\"", "status": "passed", "steps": [{"name": "Ввести значение: 04.06.2012", "status": "passed", "start": 1666593048119, "stop": 1666593048181}], "parameters": [{"name": "value", "value": "'04.06.2012'"}], "start": 1666593048119, "stop": 1666593048181}, {"name": "Заполнить поле \"Адрес регистрации\"", "status": "passed", "steps": [{"name": "Ввести значение: с. Каспийск, алл. Тургенева, д. 86 стр. 2, 612472", "status": "passed", "start": 1666593048181, "stop": 1666593048588}], "parameters": [{"name": "value", "value": "'с. Каспийск, алл. Тургенева, д. 86 стр. 2, 612472'"}], "start": 1666593048181, "stop": 1666593048588}, {"name": "Заполнить поле \"Телефон\"", "status": "passed", "steps": [{"name": "Ввести значение: +7(094)-146-98-46", "status": "passed", "start": 1666593048588, "stop": 1666593048830}], "parameters": [{"name": "value", "value": "'+7(094)-146-98-46'"}], "start": 1666593048588, "stop": 1666593048830}, {"name": "Заполнить поле \"Email\"", "status": "passed", "steps": [{"name": "Ввести значение: shubinveniamin@ip.info", "status": "passed", "start": 1666593048830, "stop": 1666593049229}], "parameters": [{"name": "value", "value": "'shubinveniamin@ip.info'"}], "start": 1666593048830, "stop": 1666593049229}], "parameters": [{"name": "value", "value": "FormData(fio='Лариса Олеговна Григорьева', birthday='17.11.1991', doc_data='5613-276830', doc_issue_date='04.06.2012', registration_address='с. Каспийск, алл. Тургенева, д. 86 стр. 2, 612472', phone='+7(094)-146-98-46', email='shubinveniamin@ip.info', add_person=True, name_insured=None, date_birth_insured=None, id_insured=None, id_dateInsured=None)"}], "start": 1666593047607, "stop": 1666593049229}, {"name": "Нажать кнопку \"Перейти к оплате\"", "status": "passed", "steps": [{"name": "Ожидание прогрузки страницы", "status": "passed", "start": 1666593049416, "stop": 1666593049735}], "start": 1666593049229, "stop": 1666593049735}, {"name": "Проверить название текущего шага.", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\n\nReason: AssertionError: actual text: 2. Ввод данных\n\n", "trace": "  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\alpik\\PycharmProjects\\absolutins\\core\\pages\\coronavirus_insurance_policy_page.py\", line 80, in assure_current_step_name\n    self._current_step_text.should(have.text(value))\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py\", line 539, in should\n    super().should(condition)\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py\", line 126, in should\n    self.wait.for_(condition)\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\wait.py\", line 125, in for_\n    raise self._hook_failure(failure)\n"}, "steps": [{"name": "Скролл к началу страницы", "status": "passed", "start": 1666593049735, "stop": 1666593049752}, {"name": "Текущий активный шаг: 3. Оплата", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.calc-steps-desktop li.current span')).has text 3. Оплата\n\nReason: AssertionError: actual text: 2. Ввод данных\n\n", "trace": "  File \"C:\\Users\\alpik\\PycharmProjects\\absolutins\\core\\pages\\coronavirus_insurance_policy_page.py\", line 80, in assure_current_step_name\n    self._current_step_text.should(have.text(value))\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py\", line 539, in should\n    super().should(condition)\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\entity.py\", line 126, in should\n    self.wait.for_(condition)\n  File \"C:\\Users\\alpik\\.virtualenvs\\absolutins\\lib\\site-packages\\selene\\core\\wait.py\", line 125, in for_\n    raise self._hook_failure(failure)\n"}, "start": 1666593049752, "stop": 1666593053758}], "parameters": [{"name": "value", "value": "'3. Оплата'"}], "start": 1666593049735, "stop": 1666593053763}], "attachments": [{"name": "failure-screenshot", "source": "3a2cc2f8-2330-4cae-a31e-a049da3390c9-attachment.png", "type": "image/png"}, {"name": "js-console-log", "source": "4caad592-72c4-4063-b686-831bd4ea353c-attachment.txt", "type": "text/plain"}, {"name": "driver-log", "source": "8cf45c66-55e0-4c48-9774-5569829670b1-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "c6f2d2e0-ae6e-4c12-95ea-d100988cb62a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "a51f1d25-3c89-4537-9f47-0a709e73dce7-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "84fc0e4e-2cce-47bf-8099-9b5d81e2a88a-attachment.txt", "type": "text/plain"}], "start": 1666593040708, "stop": 1666593053765, "uuid": "19d9984f-0453-4453-a70b-1727917f7432", "historyId": "bd6fb935a688fb1b8c47b0b9d126c04a", "testCaseId": "9d69ae75d6fc576e664ffc6416a57980", "fullName": "ui.test_form_data.TestCalculateForm#test_open_payment_form", "labels": [{"name": "subSuite", "value": "Ввод данных"}, {"name": "suite", "value": "Форма покупки полиса"}, {"name": "parentSuite", "value": "Регрессионное тестирование"}, {"name": "tag", "value": "regress"}, {"name": "tag", "value": "@pytest.mark.usefixtures('web_browser')"}, {"name": "host", "value": "DESKTOP-GMLT5VV"}, {"name": "thread", "value": "22688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ui.test_form_data"}]}